### ISSUE TITLE
Derivative of Lagrangian Interpolation 

### ISSUE THREAD

**Issue by dynamic-queries** [SciML/DataInterpolations.jl#105] opened 2022-02-05 13:40 UTC
I am curious if this is a previously known issue with the derivative computation of the Lagrangian Interpolator. 

![image](https://user-images.githubusercontent.com/81833704/152644378-4a5b2ca0-dcc0-4695-a27d-cd35e646812c.png)

**Comment by ChrisRackauckas** [comment] 2022-02-05 14:04
Thanks for the report. That issue was not known.

**Comment by dynamic-queries** [comment] 2022-02-05 14:31
I would like to dig in, If its okay!

**Comment by ChrisRackauckas** [comment] 2022-02-05 14:33
yes please do thanks!

**Comment by ChrisRackauckas** [comment] 2023-10-22 12:07
Duplicate of https://github.com/SciML/DataInterpolations.jl/issues/196#issuecomment-1773984880. The other issue is more explicit so we can keep that one.

**Closed by ChrisRackauckas** 2023-10-22 12:07 UTC
